project:
  type: book

book:
  title: "NYC Open Data Student Gallery - Brooklyn College"
  author: "Christian Martinez"
  date: "2026-01-29"
  chapters:
    - index.qmd
    - chapters/01-Final-Project-Crystal.qmd
    - chapters/02-Final-Social-Infrastructure-and-Well-Being-Jonah.qmd
    - chapters/03-Final-Restaurant-and-Museum-Project-Joyce.qmd
    - chapters/04-MSG-effect-Robert.qmd
    - chapters/05-Final-Project-Isley.qmd
    - chapters/06-ToxicHomes-Shannon.qmd
    - chapters/07-EnvironmentalStressorsandSocialComplaintsNYC-Emma.qmd
    - chapters/08-Beating-Around-the-Bush--Uncovering-the-Hidden-Link-Between-Urban-Trees-and-Wildlife-Activity-Xinru.qmd
  appendices:
    - chapters/09-references.qmd
  cover-image: images/cover.png

execute:
  freeze: auto

bibliography: packages.bib
link-citations: true
number-sections: true

website:
  search: false

format:
  html:
    theme:
      - cosmo
      - brand
    code-copy: true
